version: "3.9"

services:
  emoji-sender-api:
    container_name: emoji-sender-api
    build: .
    env_file: ./app.env
    ports:
      - "3030:3030"
    networks:
      - emoji-sender-api
      - postgres
      - postgresadmin
    volumes:
      - ./src:/app/src
      - ./ormconfig.js:/app/ormconfig.js
      - ./tsconfig.json:/app/tsconfig.json
    command: yarn run start:dev

networks:
  emoji-sender-api:
    name: emoji-sender-api
  postgres:
    external: true
  postgresadmin:
    external: true
   