version: "3.9"

services:
  emoji-sender-api:
    container_name: emoji-sender-api
    build: .
    depends_on:
      - emoji-sender-db
    env_file: ./app.env
    ports:
      - "3030:3030"
    volumes:
      - ./src:/app/src
      - ./ormconfig.json:/app/ormconfig.json
      - ./tsconfig.json:/app/tsconfig.json
    command: yarn run start:dev
  emoji-sender-db:
    container_name: emoji-sender-db
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes: 
      - emoji-sender-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: emoji
      POSTGRES_PASSWORD: emoji
      POSTGRES_DB: emoji
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - emoji-sender-db

volumes:
    emoji-sender-db:
    pgadmin-data:
